// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

Jest.describe("Root", (function (param) {
        Jest.test("true is true", (function (param) {
                return Jest.Expect.toBe(true, Jest.Expect.expect(true));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
