// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var AwsAppsync = require("aws-appsync");

function create($staropt$star, param) {
  var options = $staropt$star !== undefined ? Caml_option.valFromOption($staropt$star) : { };
  return new AwsAppsync.AWSAppSyncClient(options);
}

exports.create = create;
/* aws-appsync Not a pure module */
